spring:
  datasource:
    url: ${DB_URL}
    driver-class-name: ${DB_DRIVER}
    username: ${DB_USERNAME}
    password: ${DB_PASS}
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    contexts: docker-dev
ofertownia:
  host: ${MAIL_HOST}
  port: ${MAIL_PORT}
  userName: ${MAIL_USERNAME}
  password: ${MAIL_PASS}
  protocol: smtp
  smtpAuth: true
  starttlsEnable: true
  mailDebugEnable: false
  from: ${MAIL_USERNAME}