spring:
  liquibase:
    change-log: classpath:/db/changelog/master.xml
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    hibernate:
      ddl-auto: validate
  mail:
    host: localhost
    port: 1025
    username: security@spring.com
logging:
  level:
    org.springframework.security.web: DEBUG
jws:
  sharedKey: b55cd585-10cd-48d2-9dfa-cddc7f83f060