spring:
  liquibase:
    change-log: classpath:/db/changelog/master.xml
  profiles:
    default: dev
  h2:
    console:
      enabled: true
jws:
  sharedKey: ${SHARED_KEY}
openWeather:
  apiKey: ${API_KEY}