spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ofertownia_db?useSSL=false&serverTimezone=Europe/Warsaw
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: validate
  mail:
    host: localhost
    port: 1025 # port used by Mailpit (mail sender simulator)
    username: security@spring.com
  liquibase:
    contexts: prod
#logging:
#  level:
#    org.springframework.security.web: DEBUG